var STATE_UNKNOWN = 0, STATE_LOADING = 1, STATE_LOADED = 2, STATE_ERROR = 3;

var VIRAL_TYPE_GET = 1;
var VIRAL_TYPE_GIVEANDGET = 2;

var ACCEPT_SUCCESS = "SUCCESS";
var ACCEPT_LIMIT_REACHED = "ACCEPT_LIMIT_REACHED";
var ACCEPT_DUPLICATE = "ACCEPT_DUPLICATE";
var ACCEPT_OUT_OF_REWARDS = "ACCEPT_OUT_OF_REWARDS";
var ACCEPT_EXPIRED = "ACCEPT_EXPIRED";

//In case of default error
var UNKNOWN_ERROR = "UNKNOWN_ERROR";