var ERROR_CODE = {
    SUCCESS: 0,
    EXTENSION_DISABLED: 1,
    FEED_CLAIM_ERROR: 2,
    VERSION_UPDATE_ERROR: 3,
    LOCALE_FETCH_ERROR: 4,
    LOCALE_PARSE_ERROR: 5,
    ENTITY_TEMPLATES_FETCH_ERROR: 6,
    ENTITY_TEMPLATES_PARSE_ERROR: 7,
    MANIFEST_FETCH_ERROR: 8,
    EMPTY_FRIENDS_ERROR: 9,
    FEED_FETCH_ERROR: 10,
    SOCIAL_NETWORK_QUERY_ERROR: 11,
    PUBLISH_ERROR_LOG_ERROR: 12,
    FB_TOKEN_VALIDATE_ERROR:13,
    SESSION_INIT_ERROR:14,
    SESSION_UPDATE_ERROR:15,
    API_UPDATE_ERROR:16,
    SESSION_EXPIRED_ERROR:17,
    SETTINGS_FETCH_ERROR:18,
    ZLOC_INIT_ERROR:19,
    NOTIFICATION_PERMISSION_ERROR:20,
    NOTIFICATION_PROGRESS: 21
};



